jwt:
  secret:
    key: BExbuXAWNp6By1nefaPHt0VFoqImQ6nZ92a8kbHE

message:
  topic:
    saveMember: saveMember

spring:
  datasource:
    url: jdbc:postgresql:tcp://${DB_HOST}:${DB_PORT}/~/memberserver
    driver-class-name: org.postgresql.Driver
    username: pollify
    password: pollify

  jpa:
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    producer:
      group-id: memberserver
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.hibernate.sql: warn