apiVersion: apps/v1
kind: Deployment
metadata:
  name: memberserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memberserver
  template:
    metadata:
      labels:
        app: memberserver
    spec:
      containers:
        - name: memberserver
          image: syua0529/memberserver
          env:
            - name: DB_HOST
              value: "member-database-service.member-service.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "pollify"
            - name: DB_PASSWD
              value: "pollify"
            - name: KAFKA_HOST
              value: "kafka.kafka.svc.cluster.local"
            - name: KAFKA_PORT
              value: "9092"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
